SEED = 42

DATE_COLUMN = 'ds'

TRAIN_PERC = 0.8
NB_TRIALS = 15

FORECASTER_MODEL = 'LSTM'
FORECASTER_LOSS = 'mean_squared_error'
FORECASTER_OBJECTIVE = 'val_loss'

FORECAST_HORIZON = 7
OBSERVATION_WINDOW = 14
